{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "capwiki-nexus-registry",
    "namespace": "default",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "capwiki-nexus-registry",
        "namespace": "default",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgBOtZ/mI8WcdNe97lv3m+Fqj7ZKnUmtrZgHMBhns5spf6n1encGjQvpyB10akhSsqri2Gd/aQ4eDlIVvd4qKZaqvENmciRE9Xy1icGgkWqnFbhEcvm4Yqx6E5Fx0xC8ja8kj8WGR2uW8kNnHjlzDu/aYBHJTL3CbEYFsXWfMGsewlU2WURT9IKy1fALcQvIMoq745Lf9UooZW75co1arzHC+yeFnPy0UaoQVlfi6+7s/TDDEE7/MnIsS7lH8dLa3jrj7JPmf86ZgXZpfDYI3hSoX19TM3EI7VG+rAEGCh03A8rmk6mpL0GS+3VhBHUygAsz136xdqK7GfHJwdlVDKMoBOAQhZG4Lv+nqGOmmRtTv3GeWT3ykV+F066J6IzoXY+s4xyAf7OpmNt8TJcF9QUIUN3vKbCBGCGHewKnEdznV8Hvctl3LSpFdvxLb+5/hLPcqx/+3GjABNxYInjSziGcv9DFy8/BuxAt1TMeCILF5fXKNexyh687WZz+3cWK1R1m4CSPapHb4M82WwR8K2VOecIkzS1OMmSrppJz7DZcN2wpdVK9mJttuUg2s9BhtdpltfTCGhand1t1InT1NBF/4vwxfsrn5bVl7vE54U1k6bTEh2bKX/Ftp5rXNcmWUwdIxgDahLM4ccJot4X/vmV/tpFAtFrZK7RCVNu9lapLnbxepTNDC2X/Sx3QXIkcRIiD8uHknNqGrGHU5pLBAJL1K4jjKZhV+sLP3reSPqi9NekELjULj1lkMFHFYjn5U0D3gvUgWwFExARpiOrGM5Q4dBt5cVnMMIE/LcZXuQfjUYSOOal3oHDNUfJeGCUZu+qaBRdiuVMQIbFya8xzVzOYEvLJm6A4f7dpo2JQvd2r2vbaumJeY4/HleeVRPJvSWh+tO5u+OjDYtE8oVjvP0uA"
    }
  }
}