apiVersion: v1
kind: ServiceAccount
metadata:
  name: capwiki
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capwiki-deployer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "services", "configmap", "ingress", "secrets"]
  verbs: ["get", "list", "watch", "create","update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capwiki-deployer-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: capwiki
  namespace: default
roleRef:
  kind: Role
  name: capwiki-deployer
  apiGroup: rbac.authorization.k8s.io