{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "capwiki-nexus-registry",
    "namespace": "default",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "capwiki-nexus-registry",
        "namespace": "default",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgBPego8nwBdMhSemQyMtbT8fELTbMoAU1pQKQASwCv52CWkdfLL2mhtHdgRFqp/Ls5Sm29MBrTyffdQDdtgoSp930Du7jAAt2G3bO76H8MuD4rwpuDGowfgtZ5zD+J5v6k5Xi/oR8SF7HZ7mz9Av2Ntg/d9dzV3NAQ6VG8SrFlJ3xNfLQlJ81wtLtuCyiRJknaydrrPSFYV8RIhr3ohpTyV8s7sOSXekdhO4tQ+rg8M6mQtU7Fn686Ga4PyMnaSmD6Sa7/jkbXGJr5PJaT8ZnwWnn1rUgBV/AfTvXt6AvoluVAz5IBM3BxpFi4zePSMZi3dqRc4lQV2ZGP93OydSm4CIp0+lMeIw30VSPK/IouHivtybVqPB+WlkJqdVBoVdICuQ+1O+Av915tGes9J2x2lhx7J8QuMMV/f8D+rSVX9QQQJsq/Ay5JmDKfyHhvMz7yL/AVRUXmbhZfsIq8kyoDtvrFZc91lpwOSnwvoxrPa9jtnko3onCj4XZe/3JEwyLy5zSTmCTPGFOasP7iwiWps/gfKiL/Wsbt3Renn5n9f7Fh8h5TZ9DvH/fCJfUHbsQk1FW4AnJmiy/NXbTcd+1TfiNYJ/PeT6+Xt1Id7JfRxyW4N5HlUYzbAcALYB2ANeeR9ZgZndZkE38R3/axkmqi7XeWaWNU/OHwaERvFo535W6xN0mVc250R1aZg8BgD19e7hewhKAErsdlOqJDSKiIJxSvUb4Nhunoiz96D7fuN5bbz6EnItXVV2zU3Z6WLQK1Z1+Yp5FRcXfIG6MXVge9RLnt8cK5FtnKrGGdKtIfaFJ//N68MKh1aedI6GAGa6muQ5lmXOuSk24SipMxZjRA7wjHItcELQRlL/Tvfe2eFmaejopEOs1LESuPBjSTBbWJkVp+gi/uzS1bo2m34byKI"
    }
  }
}