apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-shared-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
