apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cr
rules:
- apiGroups: [""]
  resources: ["nodes/metrics", "pods", "services", "configmap", "secrets", "ingress"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-crb
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-cr
  apiGroup: rbac.authorization.k8s.io