query Sites($showAdminOnly: Boolean) {
    sites(showAdminOnly: $showAdminOnly) {
        id
        path
        isEnabled
        name
        showRecentActivities
        createdAt
        pageCount
    }
}
