mutation UpdateSite ($id: String!, $isEnabled: Boolean!, $name: String!, $path: String!) {
    updateSite(
        id: $id,
        patch: { isEnabled: $isEnabled, name: $name, path: $path}
    ) {
        responseResult {
            succeeded
            errorCode
            slug
            message
        }
    }
}