mutation UpdateSite ($id: String!, $isEnabled: Boolean!, $name: String!, $showRecentActivities: Boolean) {
    updateSite(
        id: $id,
        patch: { isEnabled: $isEnabled, name: $name, showRecentActivities: $showRecentActivities }
    ) {
        responseResult {
            succeeded
            errorCode
            slug
            message
        }
    }
}