mutation (
  $flags: [SystemFlagInput]!
) {
  system {
    updateFlags(
      flags: $flags
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
