mutation (
  $host: String!
  $title: String!
  $description: String!
  $robots: [String]!
  $analyticsService: String!
  $analyticsId: String!
  $company: String!
  $hasLogo: Boolean!
  $logoIsSquare: Boolean!
  $featurePageRatings: Boolean!
  $featurePageComments: Boolean!
  $featurePersonalWikis: Boolean!
  $securityIframe: Boolean!
  $securityReferrerPolicy: Boolean!
  $securityTrustProxy: Boolean!
  $securitySRI: Boolean!
  $securityHSTS: Boolean!
  $securityHSTSDuration: Int!
  $securityCSP: Boolean!
  $securityCSPDirectives: String!
) {
  site {
    updateConfig(
      host: $host,
      title: $title,
      description: $description,
      robots: $robots,
      analyticsService: $analyticsService,
      analyticsId: $analyticsId,
      company: $company,
      hasLogo: $hasLogo,
      logoIsSquare: $logoIsSquare,
      featurePageRatings: $featurePageRatings,
      featurePageComments: $featurePageComments,
      featurePersonalWikis: $featurePersonalWikis,
      securityIframe: $securityIframe,
      securityReferrerPolicy: $securityReferrerPolicy,
      securityTrustProxy: $securityTrustProxy,
      securitySRI: $securitySRI,
      securityHSTS: $securityHSTS,
      securityHSTSDuration: $securityHSTSDuration,
      securityCSP: $securityCSP,
      securityCSPDirectives: $securityCSPDirectives
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
