{
  site {
    config {
      host
      title
      description
      robots
      analyticsService
      analyticsId
      company
      logoUrl
      featurePageRatings
      featurePageComments
      featurePersonalWikis
      securityIframe
      securityReferrerPolicy
      securityTrustProxy
      securitySRI
      securityHSTS
      securityHSTSDuration
      securityCSP
      securityCSPDirectives
    }
  }
}
