{
  site {
    config {
      host
      title
      description
      keywords
      robots
      ga
      company
      hasLogo
      logoIsSquare
      featurePageRatings
      featurePageComments
      featurePersonalWikis
    }
  }
}
