mutation($strategies: [AuthenticationStrategyInput]!, $config: AuthenticationConfigInput) {
  authentication {
    updateStrategies(strategies: $strategies, config: $config) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
