query {
  authentication {
    strategies(orderBy: "title ASC") {
      isEnabled
      key
      props
      title
      useForm
      config {
        key
        value
      }
      selfRegistration
      domainWhitelist
      autoEnrollGroups
    }
  }
}
