query {
  authentication {
    strategies {
      isEnabled
      key
      title
      description
      isAvailable
      useForm
      logo
      website
      config {
        key
        value
      }
      selfRegistration
      domainWhitelist
      autoEnrollGroups
    }
  }
}
