mutation ($groupId: Int!, $userId: Int!) {
  groups {
    assignUser(groupId: $groupId, userId: $userId) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
