query {
  system {
    info {
      currentVersion
      latestVersion
      latestVersionReleaseDate
      operatingSystem
      hostname
      cpuCores
      ramTotal
      workingDirectory
      nodeVersion
      redisVersion
      redisUsedRAM
      redisTotalRAM
      redisHost
      postgreVersion
      postgreHost
    }
  }
}
