query ($id: Int!) {
  pageById(id: $id) {
    id
    path
    hash
    title
    description
    isPrivate
    isPublished
    privateNS
    publishStartDate
    publishEndDate
    content
    contentType
    createdAt
    updatedAt
    editor
    locale
    authorId
    authorName
    authorEmail
    creatorId
    creatorName
    creatorEmail
    siteId
    siteName
    sitePath
  }
}
