mutation CreatePage(
  $content: String!
  $description: String!
  $editor: String!
  $isPublished: Boolean!
  $isPrivate: Boolean!
  $locale: String!
  $path: String!
  $publishEndDate: Date
  $publishStartDate: Date
  $scriptCss: String
  $scriptJs: String
  $tags: [String!]!
  $title: String!
  $siteId: String!
  $notifyFollowers: Boolean
  $mentions: [String]
) {
  pages {
    create(
      content: $content
      description: $description
      editor: $editor
      isPublished: $isPublished
      isPrivate: $isPrivate
      locale: $locale
      path: $path
      publishEndDate: $publishEndDate
      publishStartDate: $publishStartDate
      scriptCss: $scriptCss
      scriptJs: $scriptJs
      tags: $tags
      title: $title
      siteId: $siteId
      notifyFollowers: $notifyFollowers
      mentions: $mentions
    ) {
      responseResult {
        succeeded
        message
        slug
      }
      page {
        id
        title
        path
        siteId
      }
    }
  }
}
