mutation DeletePage(
  $id: Int!
  $notifyFollowers: Boolean
  $mentions: [String]
) {
  pages {
    delete(
      id: $id
      notifyFollowers: $notifyFollowers
      mentions: $mentions
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
