variables:
  PROJECT_NAME: 'mar'
  APP_NAME: 'capwiki'
  DOCKER_REGISTRY: 'docker-registry-pt-support-shared.pl.s2-eu.capgemini.com'
  DEPLOY_USER: 'capwiki'
  TARGET_DIR: "/home/${DEPLOY_USER}/${PROJECT_NAME}"
  IMAGE: '${DOCKER_REGISTRY}/${PROJECT_NAME}/${APP_NAME}'
  PANDOC_IMAGE: '${DOCKER_REGISTRY}/${PROJECT_NAME}/pandoc'
  STAGING_IMAGE_TAG: 'latest-staging'
  STAGING_IMAGE: "${IMAGE}:${STAGING_IMAGE_TAG}"

  ENVIRONMENT:
    value: "none"
    options:
      - "none"
      - "dev1"
      - "dev2"
      - "staging"
      - "production"
    description: "Choose on which environment should pipeline run"

  IMAGE_TAG:
    value: ""
    description: "Specify the image tag for dev, use MAR-<Jira-ticket-nr> for staging (ignore i.e has default value latest-staging), for prod, use tags ex. 1.0.0 etc"

  SONARQUBE:
    value: "true"
    options:
      - "true"
      - "false"
    description: "Choose false to skip code quality check"
    
  PANDOC:
    value: "true"
    options:
      - "true"
      - "false"
    description: "Choose false to skip build & push pandoc docker image stages"

  VERSION:
     value: "1.3.0"
     description: "Update to next release version, it should be numeric value, ex: 1.0.0"

default:
  tags:
    - runner_mar
  before_script:
    - |
      rm -rf $HOME/.npm-global
      NPM_GLOBAL_DIR="$HOME/.npm-global"
      mkdir -p "$NPM_GLOBAL_DIR/bin"
      npm config set prefix "$NPM_GLOBAL_DIR"
      export PATH="$NPM_GLOBAL_DIR/bin:$PATH"
      npm install -g yarn
      node -v && npm -v && yarn -v

stages:
  - environment-set
  - build
  - test
  - sonarqube
  - modify-package-json #Need to remove this stage when MAR-444 task is done.
  - docker-build
  - docker-push #when this stage "docker push image" is success then argocd will do pull strategy to automate k8s cluster deployment based on docker image tag value
  - promote-prod-release-version

environment-set:
  stage: environment-set
  script:
    - echo "environment used for this pipeline is ${ENVIRONMENT}"
  environment:
    name: ${ENVIRONMENT}

build:
 stage: build
 script:
    - yarn cache clean
    - rm -rf node_modules
    - rm -rf yarn.lock yarn.lock
    - yarn install --frozen-lockfile --force
    - yarn build
 rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
      when: never
    - when: always

test:
  stage: test
  dependencies:
    - build
  script:
    - yarn add jest-junit --dev
    - yarn jest --coverage # Run tests
    ## Below cmnds can be run after fixing lint errors in the codebase
    #- yarn eslint --ext .js,.vue .
    # - yarn pug-lint server/views
  artifacts:
    expire_in: 1 hr
    when: on_success
    paths:
      - coverage
      - test-results
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
      when: never
    - when: on_success

sonarqube-scan:
  stage: sonarqube
  dependencies:
    - test
  tags:
    - docker_runner
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
      when: never
    - if: $SONARQUBE == "true"
      when: on_success

docker-build:
  stage: docker-build
  before_script:
    - |
      chmod +x gitlab/set-image-tag.sh
      bash gitlab/set-image-tag.sh "$ENVIRONMENT" "$IMAGE_TAG"
      source image_tag.env
      echo "Image tag is ${IMAGE_TAG_BY_ENV}"
      if [[ -z "$IMAGE_TAG_BY_ENV" ]]; then
        echo "❌ ERROR: IMAGE_TAG_BY_ENV is empty. so could not build docker image."
        exit 1
      fi
      docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
      export NEW_IMAGE="${IMAGE}:$IMAGE_TAG_BY_ENV"
      echo "Constructed NEW_IMAGE: $NEW_IMAGE"
      export NEW_PANDOC_IMAGE="${PANDOC_IMAGE}:$IMAGE_TAG_BY_ENV"
      echo "Constructed NEW_PANDOC_IMAGE: $NEW_PANDOC_IMAGE"
      rm image_tag.env
  script:
    - echo "Building Docker image for environment $ENVIRONMENT"
    - docker build --no-cache --build-arg VERSION="$VERSION" --build-arg RELEASE_DATE="$(date +'%d.%m.%Y')" -f Dockerfile -t "$NEW_IMAGE" .
    - echo "NEW_IMAGE=$NEW_IMAGE" > newimage.txt
    # Conditionally build the Pandoc image if PANDOC is set to true
    - |
      if [[ "$PANDOC" == "true" ]]; then
        echo "Building Pandoc Docker image..."
        cd dev/pandoc
        docker build --no-cache -f Dockerfile -t "$NEW_PANDOC_IMAGE" .
        cd ../..
        echo "NEW_PANDOC_IMAGE=$NEW_PANDOC_IMAGE" >> newimage.txt
      else
        echo "Skipping Pandoc Docker image build as PANDOC is not set to true."
      fi
  artifacts:
    paths:
      - newimage.txt
    expire_in: 1 hour  # Expires 1 minute after the pipeline finishes
  environment:
    name: $ENVIRONMENT
    url: $NEW_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^(feature|task|hotfix|improvement|bugfix|docs)\// && $CI_PIPELINE_SOURCE == "web" && ($ENVIRONMENT == "dev1" || $ENVIRONMENT == "dev2")'
      when: always
    - if: $CI_COMMIT_REF_NAME == "develop" || $ENVIRONMENT == "staging"
      when: always

push-docker-image:
  stage: docker-push
  needs:
   - docker-build
  before_script:
   - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
  script:
    - source newimage.txt
    - echo "Pushing Docker image"
    - docker push $NEW_IMAGE
    # Conditionally push the Pandoc image if PANDOC is set to true
    - |
      if [[ "$PANDOC" == "true" ]]; then
        echo "Push Pandoc Docker image...$NEW_PANDOC_IMAGE"
        docker push "$NEW_PANDOC_IMAGE"
        docker rmi $NEW_PANDOC_IMAGE
      fi
    - docker logout $DOCKER_REGISTRY
    - docker rmi $NEW_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^(feature|task|hotfix|improvement|bugfix|docs)\// && $CI_PIPELINE_SOURCE == "web" && ($ENVIRONMENT == "dev1" || $ENVIRONMENT == "dev2")'
      when: on_success
    - if: $CI_COMMIT_REF_NAME == "develop" || $ENVIRONMENT == "staging"
      when: on_success

promote-prod-release-version:
  stage: promote-prod-release-version
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
  script:
    - export NEW_IMAGE="${IMAGE}:$IMAGE_TAG_BY_ENV"
    - echo "upgrade Docker image to release version $VERSION"
    - echo "Staging Image is $STAGING_IMAGE"
    - |
      if ! docker pull $STAGING_IMAGE; then
        echo "Error: Staging image $STAGING_IMAGE does not exist or could not be pulled."
        exit 1
      fi
    - IMAGE_CREATED=$(docker inspect --format='{{.Created}}' $STAGING_IMAGE)
    - echo "Staging Image Created at $IMAGE_CREATED"
    - docker tag  $STAGING_IMAGE $NEW_IMAGE
    - docker push $NEW_IMAGE
    - docker logout $DOCKER_REGISTRY
    - docker rmi $STAGING_IMAGE
    - docker rmi $NEW_IMAGE
  rules:
   - if: $CI_COMMIT_REF_NAME == "main" || $ENVIRONMENT == "production"
     when: always

after_script:
    - |
      NPM_GLOBAL_DIR="$HOME/.npm-global"
      if [ -d "$NPM_GLOBAL_DIR" ]; then
          echo "Directory $TARGET_DIR exists. Deleting it..."
          rm -rf "$NPM_GLOBAL_DIR"
      fi
