services:
  db:
    container_name: wiki-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  wiki:
    container_name: wiki-app
    image: ghcr.io/requarks/wiki:2
    init: true
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: ${DB_SSL:-false}
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db-data:
