sonar.projectKey=MAR
sonar.qualitygate.wait=true

# Test report location
sonar.junit.reportPaths=test-results/report.xml

# Coverage report location (LCOV format)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Define the criteria to ignore duplicate code in dev/webpack folder
sonar.issue.ignore.multicriteria=ignoreDuplicateCodeBetweenWebpackFiles
sonar.issue.ignore.multicriteria.ignoreDuplicateCodeBetweenWebpackFiles.ruleKey=duplicated-blocks
sonar.issue.ignore.multicriteria.ignoreDuplicateCodeBetweenWebpackFiles.resourceKey=**/dev/webpack/**
