sonar.projectKey=MAR
sonar.qualitygate.wait=true

# Help Sonar correctly classify tests vs source files.
sonar.tests=server/test

# The repo includes a small Python service (pandoc). Pin version for more precise analysis.
sonar.python.version=3

# Test report location
sonar.junit.reportPaths=test-results/report.xml

# Coverage report location (LCOV format)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
