sonar.projectKey=MAR
sonar.qualitygate.wait=true

# Test report location
sonar.junit.reportPaths=test-results/report.xml

# Coverage report location (LCOV format)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
