apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/capwiki.helm.image-name: capwiki.image.repository
    argocd-image-updater.argoproj.io/capwiki.helm.image-tag: capwiki.image.tag
    argocd-image-updater.argoproj.io/capwiki.pull-secret: pullsecret:argocd/capwiki-nexus-registry
    argocd-image-updater.argoproj.io/capwiki.update-strategy: newest-build
    argocd-image-updater.argoproj.io/image-list: capwiki=docker-registry-pt-support-shared.pl.s2-eu.capgemini.com/mar/capwiki
  name: capwiki
  namespace: argocd
spec:
  destination:
    namespace: capwiki
    server: https://kubernetes.default.svc
  project: capwiki
  source:
    kustomize:
      namespace: capwiki
    path: manifests/dev1
    repoURL: https://pt-support-shared.pl.s2-eu.capgemini.com/gitlab/tpo-bu-germany/CapWiki/capwiki-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true