---

## to execute commands as "sudo" and  to avoid prompting for password when we execute playbook or become_user "deployer"
## added "deployer ALL=(ALL) NOPASSWD: ALL" to the file /etc/sudoers.d/deployer on remote vm (we can do it on all vm's by executing playbook-root.yml)

- name: Create k3s directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ username }}/k3s"
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download k3s install script
  ansible.builtin.get_url:
    url: "{{ k3s_installer }}"
    dest: "/home/{{ username }}/k3s/k3s-install.sh"
    mode: '0750'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install K3s with custom pod and service IP ranges as well as without Traefik and to set kubeconfig mode
  shell: >
        sh /home/{{ username }}/k3s/k3s-install.sh
        --disable traefik --write-kubeconfig-mode 644
        --node-name k3s-master-01
        --cluster-cidr 172.16.0.0/12
        --service-cidr 192.168.0.0/12
        --version v1.30.6+k3s1
  become_method: sudo
  args:
    creates: /usr/local/bin/k3s

- name: Ensure .kube directory exists for each user
  file:
    path: "/home/{{ username }}/.kube"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'

- name: Copy the kube config file
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'
    remote_src: yes

- name: Verify k3s installation
  shell: /usr/local/bin/k3s kubectl get nodes
  register: k3s_output
  failed_when: "k3s_output.rc != 0"
  changed_when: false

- name: Print k3s verification output
  debug:
    var: k3s_output.stdout
