apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capwiki-grafanaui-secret
  namespace: monitoring
spec:
  encryptedData:
    smtppwd: AgBTqpmeQueDItZlgXApgi34tgKRQ0s2v80MzXo7tCH1U2scq9WxaDqCNj7ScQ968m8I2oSjsS6EZzz1ssK22J/JAZeDDEyEjE+jtaMSeDmSlvAb4G5+e55wHtA4n+f5Uxb9qFsmkmUFnQ5h/2aniDc/CJx8Z0s//oxMNbEosmyUXJraI2bdC+McAwQltL2VTjPK7Z5ckdxuGLUGOC7gDZ15mYuMHrpDJCZh0odtbUNjfvVJuxKXAhLzJDkJV6Rh2s/qETrHrRqjRjZHfVbAQFAWxW7GkBs5y03Ubyxm+4ni5EaWLTyq2c5DxYT0ny9KLhaGNWZk3GDvkVnlg3/8JSghZ7pJEGMmX4a0q217HYmwqlr14M6SrXrVIckVfg1Sy0w8AaZGHHJk5qHIhUv/29xqxLe47Y+lc6apFvnApGBIZ4QImCfSQvB3UCGH2S9J/UM+8sg12Fzg0d2dc99kL/Lj1j6R8uZVzQJTiF0Y//+uopH0PzjN9ppCvMTzn1cp1yeKf47fCMU2rHGafTCqocVE1SLQAq6OlY3zXJ8SA2Zmbf9Caoy/PmxwKEVKqv9ifb7SqS1JoS20yPJkC69tTpxmMccbdKPn0MACVLO8QZC8YB7ezckgzrs/tKgoZvlRac/h3J33983M2ebJ3Ay7WGyCEmDESKmPehvKSTGW4Ns4K/kN24SVRPtdVvB3hbDtlUdudmqjYCeiriEJnRJmrbY=
    smtpuser: AgCZQatbYSwJuDr2fQTp3V1RvU7PJybxrQS4iLqR1hJI79UzhZz4gkzNZD+PJFU5Y1Ezg3Lo/Zrgw0gHCoPw05iZTUAnWWzKYT3wD2VfD0TCFCN0tZMW0OFGmU+Kdmp7BcCF/WEwiunkl6rOECvn3zJ2P627NFRgtMdDkfkniMDyyz3p4M3Ej80GO7lvMuv8T6ahRkh4d4MF7MB3LNxBibTlrILvy08TwaEoXDSe2ulWjMZhkBX2HxICFIAJgvz4tCgsn9yIsNKlSX3Py7ghxkPwSeyTZodUsFa1Y0vPiHjoQHNUzOc8+Q36wHTOnp/qR99YUN3lOqVcSjvdNoER2QTjXhYlR0IwJXvwNfW6sZMFdv4giJTWs16vaz/JB+6A6kmehzIa68ABRqH1GSfG0DVwzAQs+aA4ktGmWWvts4oV7voUjFlDT3uOMUR9ydo23fllB7abqJUr9pxoWyhCa6ngM9E4nBQPixIxlDVLCGvIfk23P9LQeXfuVZdIKakmryJazIo99F68/nwNaLZ+SJXm+h7+6+XbzwQote+Le48wSSgBATK1heL2Q0lRr83j93+GfHcZe2Tj/0Ro2e8wdFzT1NrVHKP6MQiCtGW4AiLvaN9Fps08Irhr+jpn2hIxP7Jh1JZWmpG43usz9dvJ7DI9PPSIYMbDEprMB8+TNAZ4ww9TgJLPP6OlHB3C/mCbbIQ4ePA42F7n/6PfKYKP4zQMA9xY69qqZ6+Cu9F//GA1pIK+
  template:
    metadata:
      creationTimestamp: null
      name: capwiki-grafanaui-secret
      namespace: monitoring