#example to deploy on staging: ansible-playbook monitoring-playbook.yaml -i inventory  -e hostname=staging -vv
## on dev2 :  ansible-playbook monitoring-playbook.yaml -i inventory  -e hostname=dev2 -vv
---
- name: Deploy monitoring setup
  hosts: "{{ hostname }}"
  become: false  # Ensure that only user privileges are used
  become_user: "{{ username  }}" 
  vars:
   username : "deployer"
  tasks:
   - name: Create target directory for monitoring configuration
     ansible.builtin.file:
      path: "/home/{{ username }}/monitoring"
      state: directory
      mode: '0700'
      owner: "{{ username }}"
      group: "{{ username }}"

   - name: Copy deploy script and helm chart values yaml files to the remote machine and set permissions
     copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ username  }}" 
        group: "{{ username  }}" 
        mode: '0755'
     loop:
        - { src: './deploy.sh', dest: '/home/deployer/monitoring/deploy.sh' }
        - { src: './ingress/monitoring-capwiki-tls-secret.yaml', dest: '/home/deployer/monitoring/monitoring-capwiki-tls-secret.yaml' }
        - { src: './capwiki-grafanaui-secret.yaml', dest: '/home/deployer/monitoring/capwiki-grafanaui-secret.yaml' }
        - { src: './values-capwiki-kube-prom.yaml', dest: '/home/deployer/monitoring/values-capwiki-kube-prom.yaml' }
        - { src: './values-blackbox-exporter.yaml', dest: '/home/deployer/monitoring/values-blackbox-exporter.yaml' }
        - { src: './values-loki.yaml', dest: '/home/deployer/monitoring/values-loki.yaml' }
        - { src: './values-loki-prod.yaml', dest: '/home/deployer/monitoring/values-loki-prod.yaml' }
  
   - name: Copy ingress file based on hostname
     copy:
      src: "./ingress/monitoring-ingress-{{ hostname }}-cluster.yaml"
      dest: "/home/deployer/monitoring/monitoring-ingress-{{ hostname }}-cluster.yaml"
      owner: "{{ username  }}" 
      group: "{{ username  }}" 
      mode: '0755'
     when: hostname in ['dev1', 'dev2', 'staging', 'prod']

   - name: Run deploy script on remote host via SSH from the controller
     shell: |
         cd /home/{{username}}/monitoring
         ./deploy.sh {{ hostname }}

   - name: Cleanup monitoring configuration
     file: 
      state: absent
      path: "/home/{{ username }}/monitoring"
      owner: "{{ username }}"
      group: "{{ username }}"
  