affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-master-01

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator; https://github.com/coreos/prometheus-operator for each target
  enabled: true
  # Default values that will be used for all ServiceMonitors created by `targets`
  defaults:
    labels:
      release: capwiki-prometheus
    interval: 30s
    scrapeTimeout: 30s
    module: http_2xx
  ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
  scheme: http
  ## path: HTTP path. Needs to be adjusted, if web.route-prefix is set
  path: "/probe"
## Add or modify service endpoints
  targets:
     - name: capwiki-staging-website
       url: https://test-capwiki.corp.capgemini.com
     - name: capwiki-svc-test
       url: capwiki-svc.staging:80
     - name: capwiki-postgresdb
       url: capwiki-postgresdb.staging:5432