loki:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  isDefault: false
  image:
    tag: 2.9.7
  config:
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h #@TODO make it 48 or 72 hrs after testing
      retention_period: 168h
    compactor:
      retention_enabled: true
      retention_delete_delay: 1h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

fluent-bit:
  enabled: false

promtail:
  enabled: true
  config:
    logLevel: debug
    # serverPort: 3101
    # clients:
    #   - url: "http://loki.monitoring:3100/loki/api/v1/push"