loki:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  isDefault: false
  image:
    tag: 2.9.7
  compactor:
    working_directory: /data/retention
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  limits_config:
    retention_period: 120h

  schema_config:
    configs:
      - from: "2020-07-31"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem  
        schema: v13
        store: tsdb

  storage_config:
    filesystem:
      directory: /data/loki  # Path where Loki will store data on the local filesystem
    tsdb_shipper:
      active_index_directory: /data/index
      cache_location: /data/index_cache
      shared_store: filesystem 

fluent-bit:
  enabled: false

promtail:
  enabled: true
  config:
    logLevel: debug
    # serverPort: 3101
    # clients:
    #   - url: "http://loki.monitoring:3100/loki/api/v1/push"

 
