#Prefer to use cron job on Production vm
#example to run backup of postgres in staging k8s namespace on staging vm: ansible-playbook backup-playbook.yaml -i inventory  -e hostname=staging -vv
- name: Configure cron jobs
  hosts: "{{ hostname }}"
  become: false
  become_user: "{{ username }}"
  vars:
   username : "deployer"
  roles:
    - role: cron
