---
- name: Ensure apt is up to date
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install Docker CLI
  apt:
    name: docker-ce-cli
    state: present
    update_cache: yes

- name: Ensure the user exists
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    createhome: yes

- name: Create .ssh directory
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_public_keys }}"

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure the new group is created
  group:
    name: docker
    state: present

- name: Add an existing user to the new group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
    state: present
  loop:
    - gdamen
    - hgurudu
    - pebauer
    - deployer
