#example to deploy on dev2: ansible-playbook argocd-capwiki-deploy-playbook.yaml -i inventory  -e env=dev2 -vv
---
- name: Configure and Deploy capwiki application in argocd based on environment
  hosts: "{{ env }}"
  vars:
    username: "deployer"
    kubeconfig_path: "~/.kube/config"
  become: false  # Use the specified user privileges
  become_user: "{{ username }}"
  tasks:
    - name: Create target directory for Argo CD configuration
      ansible.builtin.file:
        path: "/home/{{ username }}/argocd-deploy"
        state: directory
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Copy provisioning manifests to the target dircetory
      ansible.builtin.copy:
        src: "../capwiki"
        dest: "/home/{{ username }}/argocd-deploy/"
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Copy deploy-argo bash script to the target dircetory
      ansible.builtin.copy:
        src: "../deploy-argo.sh"
        dest: "/home/{{ username }}/argocd-deploy/"
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"
    
    - name: Deploy capwiki application Kubernetes manifests
      ansible.builtin.shell: |
        cd /home/{{ username }}/argocd-deploy
        ./deploy-argo.sh {{ env }}

    - name: Cleanup Argo CD files after deployment
      ansible.builtin.file:
        path: "/home/{{ username }}/argocd-deploy"
        state: absent

