query ($id: Int!) {
  groups {
    single(id: $id) {
      id
      name
      isSystem
      permissions
      pageRules {
        id
        path
        roles
        match
        deny
        locales
      }
      users {
        id
        name
        email
      }
      createdAt
      updatedAt
    }
  }
}
