mutation ($id: Int!, $name: String!, $permissions: [String]!, $pageRules: [PageRuleInput]!) {
  groups {
    update(id: $id, name: $name, permissions: $permissions, pageRules: $pageRules) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
