query {
  pages {
    list(limit: 10, orderBy: UPDATED, orderByDirection: DESC) {
      id
      locale
      path
      title
      description
      contentType
      isPublished
      isPrivate
      privateNS
      createdAt
      updatedAt
    }
  }
}
