query {
  logging {
    loggers(orderBy: "title ASC") {
      isEnabled
      key
      title
      description
      logo
      website
      level
      config {
        key
        value
      }
    }
  }
}
