apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: monitoring-capwiki.corp.capgemini.com
    http:
      paths:
      - pathType: Prefix
        path: / 
        backend:
          service:
            name: capwiki-prometheus-grafana
            port:
              number: 80
  tls:
  - hosts:
    - monitoring-capwiki.corp.capgemini.com
    secretName: monitoring-capwiki-tls
status:
    loadBalancer:
      ingress:
      - ip: 10.40.233.65
   