mutation DeleteFollower($siteId: String!, $pageId: Int) {
  deleteFollower(siteId: $siteId, pageId: $pageId) {
    responseResult {
      succeeded
      errorCode
      slug
      message
    }
  }
}
