---
- name: Create helm directory
  file:
    path: "/home/{{ username }}/helm"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download Helm installation script
  get_url:
    url: "{{ helm_installer }}"
    dest: "/home/{{ username }}/helm/get_helm.sh"
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Run Helm installation script
  command: "/home/{{ username }}/helm/get_helm.sh"
  args:
    creates: /usr/local/bin/helm

- name: Test helm Installation
  ansible.builtin.command: helm list
  register: helm_output
  failed_when: "helm_output.rc != 0"
  changed_when: false

- name: Print helm verification output
  debug:
    var: helm_output.stdout_lines
