{
  localization {
    locales {
      availability
      code
      createdAt
      isInstalled
      installDate
      isRTL
      name
      nativeName
      updatedAt
    }
    config {
      locale
      autoUpdate
      namespacing
      namespaces
    }
  }
}
