{
  locales {
    availability
    code
    createdAt
    isInstalled
    installDate
    isRTL
    name
    nativeName
    updatedAt
  }
  localizationConfig {
    locale
    autoUpdate
    namespacing
    namespaces
  }
}
