mutation ($recipientEmail: String!) {
  mail {
    sendTest(recipientEmail: $recipientEmail) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
