{
  mailConfig {
    senderName
    senderEmail
    host
    port
    name
    secure
    verifySSL
    user
    pass
    useDKIM
    dkimDomainName
    dkimKeySelector
    dkimPrivateKey
    allowedDomains
  }
}
