query {
  search {
    searchEngines(orderBy: "title") {
      isEnabled
      key
      title
      description
      logo
      website
      isAvailable
      config {
        key
        value
      }
    }
  }
}
