query {
  search {
    searchEngines(orderBy: "title ASC") {
      isEnabled
      key
      title
      description
      logo
      website
      config {
        key
        value
      }
    }
  }
}
