mutation($searchEngines: [SearchEngineInput]) {
  search {
    updateSearchEngines(searchEngines: $searchEngines) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
