mutation($providers: [AnalyticsProviderInput]!) {
  analytics {
    updateProviders(providers: $providers) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
