module.exports = {
  SAFE_SEND_MAX_RETRIES: 10,
  DELAY_MS_CREATE_QUEUE: 5000,
  DELAY_MS_SEND_AFTER_MAX: 5000,
  DELAY_MS_SEND_AFTER_MIN: 500,
  DELAY_MS_WAIT_FOR_JOB_COMPLETION: 60000,
  DELAY_MS_WAIT_FOR_JOB_POLL: 100,
  DELAY_MS_SAFE_SEND_RETRY: 200,
  JOB_RETENTION_HOURS: 6,
  JOB_POLLING_INTERVAL_SECONDS: 0.5,
  DEFAULT_ACTIVE_JOB_EXPIRATION_MINUTES: 5,
  DEFAULT_CONCURRENT_NUMBER_OF_WORKERS_FOR_RENDER_PAGE_JOB: 3,
  DEFAULT_CONCURRENT_NUMBER_OF_WORKERS_FOR_REBUILD_TREE_JOB: 3,
  DEFAULT_CONCURRENT_NUMBER_OF_WORKERS_FOR_SANITIZE_SVG_JOB: 3
}
