module.exports = {
  SAFE_SEND_MAX_RETRIES: 10,
  DELAY_MS_CREATE_QUEUE: 5000,
  DELAY_MS_SEND_AFTER_MAX: 5000,
  DELAY_MS_SEND_AFTER_MIN: 500,
  DELAY_MS_WAIT_FOR_JOB_COMPLETION: 60000,
  DELAY_MS_WAIT_FOR_JOB_POLL: 200,
  DELAY_MS_SAFE_SEND_RETRY: 200,
  JOB_RETENTION_HOURS: 6,
  JOB_POLLING_INTERVAL_SECONDS: 1
}
