{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "wiki.fullname" . }}
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
        - kind: Service
          name: {{ include "wiki.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end -}}
