mutation ($parentFolderId: Int!, $slug: String!, $siteId: String!) {
  assets {
    createFolder(parentFolderId:$parentFolderId, slug: $slug, siteId: $siteId) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
