mutation ($parentFolderId: Int!, $slug: String!) {
  assets {
    createFolder(parentFolderId:$parentFolderId, slug: $slug) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
