query ($root: String, $kind: AssetKind!) {
  assets {
    list(root:$root, kind: $kind) {
      id
      filename
      ext
      kind
      mime
      fileSize
      createdAt
      updatedAt
    }
  }
}
