mutation(
  $theme: String!
  $iconset: String!
  $darkMode: Boolean!
  $tocDepth: RangeInput!
  $injectCSS: String
  $injectHead: String
  $injectBody: String
  ) {
  theming {
    setConfig(
      theme: $theme
      iconset: $iconset
      darkMode: $darkMode
      tocDepth: $tocDepth
      injectCSS: $injectCSS
      injectHead: $injectHead
      injectBody: $injectBody
      ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
