query {
  theming {
    config {
      theme
      iconset
      darkMode
      tocDepth {
        min
        max
      }
      tocPosition
      injectCSS
      injectHead
      injectBody
    }
  }
}
