query {
  theming {
    config {
      theme
      iconset
      darkMode
      tocPosition
      injectCSS
      injectHead
      injectBody
      customFonts {
        id
        family
        filename
        format
        weight
        style
        unicodeRange
      }
    }
  }
}
