mutation($providers: [PageNavigationProviderInput]!) {
  pageNavigation {
    updateProviders(providers: $providers) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
