query {
  system {
    info {
      configFile
      currentVersion
      dbType
      dbVersion
      dbHost
      latestVersion
      latestVersionReleaseDate
      operatingSystem
      hostname
      cpuCores
      ramTotal
      workingDirectory
      nodeVersion
      redisVersion
      redisUsedRAM
      redisTotalRAM
      redisHost
    }
  }
}
