{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "capwiki-nexus-registry",
    "namespace": "argocd",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "capwiki-nexus-registry",
        "namespace": "argocd",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgCIGs4ZPtbc4Y4MlDHKnix/wlYb/P0yGpNWO3dNeDXytLw//b2VZ+c6Gu7cCnpWo7N87KYF2y3F9E6mW9ThF2+mNawi16l4K7P/2mdsk48gkKxfZwVULGxMIAhqZywEtC5Tot8MbeQKkF3l/SIwxU7U+g9Zh9H40Onjum/6t+ZZMSZBLqJB6qojOBTGDTjzzGeMAZiPyVSBrYJwfJstJoztZk+DsU1nEx/ycHe2mEBlz0xDwSDPsR6yScI6n3JNqPBRMVBzeJAxfMQtFQxMw7KsXyH1d8EyF48weyMPCPIh5n86WFug12XcV67MAPgJ9aBsxlAYMZo0XRoFzzqPE+hns7/MMMomD5TSfBZWlVTWQ3V+TdwM715rbUmek2SK0Any4ThKnXewQqbQ+6OxGg+qrIrGyUYW/1gGMj4xzI9fTLlKBI2a7MyavABZonTHwO0wO7zF0XxiPWRbzGWoy3mq5rF5b3cP//jJPIFR9pTUUA8lAaUvgkBrLJVm14Oiwe/HtErPgNsdaJpsVoQGA+DBVND/jb4Kb9GZKtyvB1RcgDeVv6N1rLwwL8rXJ8k29ibV/NZ36FFzkOkpyFsex8x1+WLX2R9i2M257AT/K9JelGPG5o6SC5aVZaNmP1y8qVonPi8+OXQl1jZDwea6FfpW0GX85GDthMBHLn8aMpmVx/6P8gMQjAfvLF8vFRlVEIG/pkI6a3YdFOWJ0AH3kgzGf/HRozzhIBymej70eTN4/OXSD8flSPGeebSmBqMLzDrutpiERbPYA670S+paPDfhz8x/i8CgyVjl2NSqY8EYdvY8o1SXsK1W7NSERIuyOK5FhW0YzkpSIgr6Ey9vedCifgWV+AYg8Qq7pJLSqj7+O9DakgM+yppJPaCZHEnsq5y8p0EOjSpfM3nuc1HlJGi8"
    }
  }
}
