---
- name: Install Docker on all machines
  hosts: all
  become: true
  roles:
    - role: install-docker

- name: Configure users on all machines
  hosts: all
  become: true
  roles:
    - role: user-provisioning

- name: Configure cron jobs
  hosts: prod
  become: true
  roles:
    - role: cron
