---
## example to run playbook on dev1:  ansible-playbook playbook-uninstall-kubernetes.yml -i inventory -e "host=dev1"  
## example to run playbook on all:  ansible-playbook playbook-uninstall-kubernetes.yml -i inventory -e "host=all" 

## ## to  execute playbook as user "deployer" (the user in host), need sudo permissions.
## added "deployer ALL=(ALL) NOPASSWD: ALL" to the file /etc/sudoers.d/deployer on remote vm (we can do it on all vm's by executing playbook-root.yml)
- name: Uninstall k3s, helm and nginx ingress on all machines
  hosts: "{{ host }}"
  become: true
  roles:
    - role: uninstall-ingress-helm-k3s
