query ($query: String!) {
  pages {
    search(query:$query) {
      results {
        id
        title
        description
        snippet
        path
        locale
      }
      suggestions
      totalHits
    }
  }
}
