query ($limit: Int, $orderBy: PageOrderBy, $orderByDirection: PageOrderByDirection, $tags: [String!], $locale: String) {
  pages {
    list(limit: $limit, orderBy: $orderBy, orderByDirection: $orderByDirection, tags: $tags, locale: $locale) {
      id
      locale
      path
      title
      description
      createdAt
      updatedAt
      tags
    }
  }
}
