query ($parent: Int!, $mode: PageTreeMode!, $locale: String!, $siteId: String!) {
  pages {
    tree(parent: $parent, mode: $mode, locale: $locale, siteId: $siteId) {
      id
      path
      title
      isFolder
      pageId
      parent
    }
  }
}
