mutation ($id: Int!, $notifyFollowers: Boolean!) {
  pages {
    delete(id: $id, notifyFollowers: $notifyFollowers) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
