query ($query: String!, $siteId: String!) {
  searchPages(query: $query, siteId: $siteId) {
    results {
      id
      title
      description
      path
      locale
      source
    }
    suggestions
    totalHits
  }
}
