query ($parent: Int!, $mode: PageTreeMode!, $locale: String!) {
  pages {
    tree(parent: $parent, mode: $mode, locale: $locale) {
      id
      path
      title
      isFolder
      pageId
      parent
    }
  }
}
