query ($limit: Int, $orderBy: PageOrderBy, $orderByDirection: PageOrderByDirection, $tags: [String!], $locale: String, $siteId: String) {
  pages {
    list(limit: $limit, orderBy: $orderBy, orderByDirection: $orderByDirection, tags: $tags, locale: $locale, siteId: $siteId) {
      id
      locale
      path
      title
      description
      createdAt
      updatedAt
      tags,
      siteId,
      sitePath
    }
  }
}
