query (
  $pageId: Int!,
  $locale: String!,
  $siteId: String!
  ) {
  childPages(pageId: $pageId, locale: $locale, siteId: $siteId) {
    id
    path
    title
    isFolder
    pageId
    parent
    locale
    siteId
    child_position
  }
}
