mutation($continuationToken: String!, $newPassword: String!) {
  authentication {
    loginChangePassword(continuationToken: $continuationToken, newPassword: $newPassword) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
      jwt
    }
  }
}
