mutation($username: String!, $password: String!, $strategy: String!) {
  authentication {
    login(username: $username, password: $password, strategy: $strategy) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
      jwt
      mustChangePwd
      mustProvideTFA
      continuationToken
    }
  }
}
