mutation($loginToken: String!, $securityCode: String!) {
  authentication {
    loginTFA(loginToken: $loginToken, securityCode: $securityCode) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
