mutation($sourceLocale: String!, $targetLocale: String!) {
  pages {
    migrateToLocale(sourceLocale: $sourceLocale, targetLocale: $targetLocale) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
      count
    }
  }
}
