{{- $ext := .Values.externalDatabase }}
{{- $useUrl := include "wiki.db.useUrl" . }}
{{- $dbUrl := and $useUrl $ext.connectionString.value }}
{{- $dbPassword := and (not .Values.postgresql.enabled) (not $useUrl) (not $ext.parameters.existingSecret) }}
{{- $adminPassword := and .Values.admin.password (not .Values.admin.existingSecret) }}
{{- if or $dbUrl $dbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki.fullname" . }}-db
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $dbUrl }}
  url: {{ $ext.connectionString.value | b64enc | quote }}
  {{- else }}
  password: {{ $ext.parameters.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if $adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki.fullname" . }}-admin
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.admin.password | b64enc | quote }}
{{- end }}
