port: 3000
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
logLevel: info
pool:
  min: 2
  max: 20
  acquireTimeoutMillis: 30000
  createTimeoutMillis: 30000
  idleTimeoutMillis: 30000
