#kubectl kustomize --enable-helm . > resources.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: charts

helmCharts:
  - name: capwiki
    # The name of the release
    releaseName: capwiki
    includeCRDs: false
    #version: v2.0.1