# ===============================================
# THEMES
# ===============================================

extend type Query {
  theming: ThemingQuery
}

extend type Mutation {
  theming: ThemingMutation
}

# -----------------------------------------------
# QUERIES
# -----------------------------------------------

type ThemingQuery {
  themes: [ThemingTheme] @auth(requires: ["manage:theme", "manage:system"])
  config: ThemingConfig @auth(requires: ["manage:theme", "manage:system"])
}

# -----------------------------------------------
# MUTATIONS
# -----------------------------------------------

type ThemingMutation {
  setConfig(
    theme: String!
    iconset: String!
    darkMode: Boolean!
    tocPosition: String
    injectCSS: String
    injectHead: String
    injectBody: String
    customFonts: [CustomFontInput]
  ): DefaultResponse @auth(requires: ["manage:theme", "manage:system"])
}

# -----------------------------------------------
# TYPES
# -----------------------------------------------

type ThemingConfig {
  theme: String!
  iconset: String!
  darkMode: Boolean!
  tocPosition: String
  injectCSS: String
  injectHead: String
  injectBody: String
  customFonts: [CustomFont]
}

type CustomFont {
  id: String!
  family: String!
  filename: String!
  format: String!
  weight: Int!
  style: String!
  unicodeRange: String
}

input CustomFontInput {
  id: String!
  family: String!
  filename: String!
  format: String!
  weight: Int!
  style: String!
  unicodeRange: String
}

type ThemingTheme {
  key: String
  title: String
  author: String
}
