mutation($targets: [StorageTargetInput]!) {
  storage {
    updateTargets(targets: $targets) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
