query {
  storage {
    targets {
      isAvailable
      isEnabled
      key
      title
      description
      logo
      website
      supportedModes
      mode
      hasSchedule
      syncInterval
      syncIntervalDefault
      config {
        key
        value
      }
      actions {
        handler
        label
        hint
      }
    }
  }
}
