mutation($strategies: [AuthenticationStrategyInput]) {
  authentication {
    updateStrategies(strategies: $strategies) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
