query {
  storage {
    targets(orderBy: "title ASC") {
      isEnabled
      key
      title
      description
      logo
      website
      mode
      config {
        key
        value
      }
    }
  }
}
