mutation($targetKey: String!, $handler: String!) {
  storage {
    executeAction(targetKey: $targetKey, handler: $handler) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
