# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wiki
      MYSQL_PASSWORD: wikijsrocks
      MYSQL_USER: wikijs
      MYSQL_ROOT_PASSWORD: wikijsrocks
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wikinet
    ports:
      - "13306:3306"

  adminer:
    image: adminer:latest
    logging:
      driver: "none"
    networks:
      - wikinet
    ports:
      - "3001:8080"

  wiki:
    build:
      context: .
      dockerfile: dev/docker-mysql/Dockerfile
    depends_on:
      - db
    networks:
      - wikinet
    ports:
      - "3000:3000"
    volumes:
      - .:/wiki
      - /wiki/node_modules
    command: ["sh", "./dev/docker-mysql/init.sh"]

networks:
  wikinet:

volumes:
  db-data:
