server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # - job_name: system
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: varlogs
  #         host: ${HOSTNAME}
  #         __path__: /var/log/**
  - job_name: docker_scrapeD
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'


  # - job_name: docker
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 60s
  #   pipeline_stages:
  #     - static_labels:
  #         host: ${HOSTNAME}
  #   relabel_configs:
  #     - source_labels: ['__meta_docker_container_name']
  #       regex: '/(.*)'
  #       target_label: 'container'
