apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capwikidevtls
spec:
  secretName: capwikidevtls
  dnsNames:
  - capwiki.corp.capgemini.com
  issuerRef:
    name: letsencrypt-dev
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer