apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
    service.beta.kubernetes.io/do-loadbalancer-hostname: capwiki.corp.capgemini.com
spec:
  selector:
   # Adjust to match with label(s) of the nginx ingress controller pod
    name: nginx-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443