mutation($renderers: [RendererInput]) {
  rendering {
    updateRenderers(renderers: $renderers) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
