query ($id: Int!) {
  users {
    single(id: $id) {
      id
      name
      email
      providerKey
      providerId
      location
      jobTitle
      timezone
      isSystem
      isActive
      isVerified
      createdAt
      updatedAt
      groups {
        id
        name
      }
    }
  }
}
