apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capwiki-internal-tls-sealed.yaml
  - resources.yaml
  - capwiki-config.yaml

patchesStrategicMerge:
  - ./patches/ingress.yaml

patches:
  - target:
      kind: Deployment
      name: capwiki-app
    path: patches/namespace-patch.yaml
  - target:
      kind: Ingress
      name: capwiki-ingress
    path: patches/namespace-patch.yaml
  - target:
      kind: StatefulSet
      name: capwiki-postgresdb
    path: patches/namespace-patch.yaml
  - target:
      kind: Service
      name: capwiki-svc
    path: patches/namespace-patch.yaml
  - target:
      kind: Service
      name: capwiki-postgresdb
    path: patches/namespace-patch.yaml
  - target:
      kind: Service
      name: capwiki-postgresdb-headless
    path: patches/namespace-patch.yaml
  - target:
      kind: Secret
      name: capwiki-nexus-registry
    path: patches/namespace-patch.yaml
  - target:
      kind: ServiceAccount
      name: capwiki-deploy-sa
    path: patches/namespace-patch.yaml
  - target:
      kind: ServiceAccount
      name: capwiki-postgresdb
    path: patches/namespace-patch.yaml
