## Custom resource configuration
crds:
  # -- Install and upgrade CRDs
  install: false
  
global:
  domain: dev2-argocd-capwiki.corp.capgemini.com

configs:
  cm:
    kustomize.buildOptions: --enable-helm
  params:
    server.insecure: true
  secret:
    argocdServerAdminPassword: "$2a$10$D/eqFQsMlFHF57c134nNcudYl38H8VF/gfZLMf4J6gVzK887xlL5i"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
    - hosts:
      - dev2-argocd-capwiki.corp.capgemini.com
      secretName: argo-server-tls

