---
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Ensure apt is up to date
  apt:
    update_cache: yes

- name: Add Docker's APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: docker-ce
    update_cache: yes

- name: Install Docker CLI
  apt:
    name: docker-ce-cli
    update_cache: yes

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure the new group is created
  group:
    name: docker
