variables:
  TRIVY_VERSION: "latest"
  POSTGRES_IMAGE_NAME: "postgresql"
  CAPWIKI_IMAGE_NAME: "capwiki"
  POSTGRES_IMAGE: "docker.io/bitnami/postgresql:15.8.0"
  CAPWIKI_IMAGE: "$DOCKER_REGISTRY/$PROJECT_NAME/$APP_NAME:feature-mar-46-cicd-k8s-healthcheck-rollback"
  TRIVY_USERNAME: "$DOCKER_REGISTRY_USER"
  TRIVY_PASSWORD: "$DOCKER_REGISTRY_PASS"

stages:
  - scan

.scan_template: &scan_template
  stage: scan
  tags:
  - docker_runner
  allow_failure: true
  image:
    name: aquasec/trivy:$TRIVY_VERSION
    entrypoint: [""]
  artifacts:
    when: always
    paths:
      - trivy-report-*.json
      - trivy-report-*.html
  

.trivy_script_template: &trivy_script_template
  - trivy image --no-progress --timeout 30m --format json --output trivy-report-$IMAGE_NAME.json $IMAGE
  - trivy convert --format template --template "@/contrib/html.tpl" --output trivy-report-$IMAGE_NAME.html trivy-report-$IMAGE_NAME.json
  - trivy image --no-progress --severity MEDIUM,HIGH,CRITICAL --exit-code 1 $IMAGE

scan_postgres_image:
  <<: *scan_template
  variables:
    IMAGE_NAME: $POSTGRES_IMAGE_NAME
    IMAGE: $POSTGRES_IMAGE
  script:
    - *trivy_script_template

scan_capwiki_image:
  <<: *scan_template
  variables:
    IMAGE_NAME: $CAPWIKI_IMAGE_NAME
    IMAGE: $CAPWIKI_IMAGE
  script:
    - *trivy_script_template

scan_monitoring_helm:
  <<: *scan_template
  script:
    - apk add bash curl openssl
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3; chmod 700 get_helm.sh; ./get_helm.sh
    - helm plugin install https://github.com/nikhilsbhat/helm-images
    - cd deployment/pipelines/scanning/
    - chmod +x scripts/helm_repo_add.sh; scripts/helm_repo_add.sh
    - chmod +x scripts/helm_scanner.sh; scripts/helm_scanner.sh
  artifacts:
    paths:
      - "deployment/pipelines/scanning/*.json"
      - "deployment/pipelines/scanning/*.html"